# Stage 1: Use Ubuntu base image
FROM ubuntu:22.04 as ubuntu-stage

# Install all required packages in a single step
RUN yes | unminimize && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
      software-properties-common \
      language-pack-en-base \
      debconf-utils \
      curl \
      net-tools \
      wget \
      nano \
      vim \
      less \
      iproute2 \
      python3 \
      python3-pip \
      jq \
      man-db \
      openssh-client && \
    rm -rf /var/lib/apt/lists/*

# Install Paramiko via pip
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir --break-system-packages paramiko


# Setup Environment variables
ENV INSTRUCTOR_SCRIPTS="/home/.evaluationScripts" \
    LAB_DIRECTORY="/home/labDirectory" \
    PATH="/home/.evaluationScripts:${PATH}" \
    TERM=xterm-256color

# Setup Directory Structure & Global Settings
RUN mkdir -p /home/labDirectory /home/.evaluationScripts && \
    echo "cd /home/labDirectory" > /root/.bashrc && \
    echo "alias ls='ls --color=always'" >> /root/.bashrc && \
    echo "rm -f \`find /home -type f -name \"._*\"\`" >> /root/.bashrc

# Default command: keep container alive
CMD [ "/bin/bash", "-c", "while :; do sleep 10; done" ]